# This is a basic workflow to help you get started with Actions

name: My-Action-Github

on:
  push:
    branches: [ master ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run linter
      run: make lint
      
      
