#----------------------
name: My-Action-Github

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: ls -la && make install
        
      - name: lint
        run: make lint
